### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by Angelnian** [Dekai21/Multi_Agent_Intersection#7]
Hello, I would like to ask, in the paper you also used inD dataset for training and testing, but in the code you use sumo data collection for training, so the final training did not use inD dataset?

**Comment by Dekai21** [comment]
Hi @Angelnian, thanks for your interest! we only used the InD dataset for the offline experiment, but for the online control experiment, we only use the sumo synthetic data.

**Comment by Angelnian** [comment]
Thank you very much for your answer！
