### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by Angelnian** [Dekai21/Multi_Agent_Intersection#8]
Hello, during the training, I also encountered the problem of excessive training loss and verification loss, may I ask what is the reason for this? Thank you very much for your patient answer！
![11](https://github.com/user-attachments/assets/fa500795-f348-4ff4-9477-21604e5ea198)

**Comment by Dekai21** [comment]
> Hello, during the training, I also encountered the problem of excessive training loss and verification loss, may I ask what is the reason for this? Thank you very much for your patient answer！ ![11](https://private-user-images.githubusercontent.com/117651188/364321319-fa500795-f348-4ff4-9477-21604e5ea198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDAxMTgsIm5iZiI6MTcyNTg5OTgxOCwicGF0aCI6Ii8xMTc2NTExODgvMzY0MzIxMzE5LWZhNTAwNzk1LWYzNDgtNGZmNC05NDc3LTIxNjA0ZTVlYTE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNjM2NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzZjNDFiNjUwYjFhNTY1ZjdhZTEzNTA5OTU2MDUyZGJjYTBhNzczOGM2MWM4NmI4NWUyNTBjOGYyZWIyZjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fl1WYhtxlWwhKaGDj8tN99BWm3BQbtARwjCC1-fPgmk)

Hi @Angelnian, thanks for your interest. Though the magnitude of the training loss looks pretty large, the ADE seems ok, have you tried to visualize the inference results?
